# Comment to a new issue.
issuesOpened: >
  Velero maintainers monitors for Issues but if you haven’t heard anything from us within 5 business days,
  
  please post on #velero-dev If your Issue is more urgent, feel free to ping us sooner on this channel and let us know.

pullRequestOpened: >
  Velero maintainers review PRs on a weekly basis. So, if you haven’t heard anything from us within 5 business days,
  
  please post on #velero-dev If your PR is more urgent, feel free to ping us sooner on this channel and let us know.
